# src/llm_policy/thresholds/extract/default.yaml
max_error_rate: 0.05
max_5xx_rate: 0.01
max_transport_error_rate: 0.01

min_schema_validity_rate: 0.90
min_required_present_rate: null
min_doc_required_exact_match_rate: null

min_field_exact_match_rate: {}
max_latency_p95_ms: null
max_latency_p99_ms: null
min_n_total: 20