"""create core tables

Revision ID: 4b11bcee269e
Revises: 32dab146fc14
Create Date: 2025-09-04 11:09:29.918347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b11bcee269e'
down_revision: Union[str, Sequence[str], None] = '32dab146fc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_id', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('params_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'prompt_hash', 'params_fingerprint', name='uq_completion_key')
    )
    op.create_index('ix_cache_model_promptfp', 'completion_cache', ['model_id', 'params_fingerprint'], unique=False)
    op.create_index(op.f('ix_completion_cache_created_at'), 'completion_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_completion_cache_model_id'), 'completion_cache', ['model_id'], unique=False)
    op.create_index(op.f('ix_completion_cache_params_fingerprint'), 'completion_cache', ['params_fingerprint'], unique=False)
    op.create_index(op.f('ix_completion_cache_prompt_hash'), 'completion_cache', ['prompt_hash'], unique=False)
    op.create_table('inference_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('client_host', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=256), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_logs_api_key'), 'inference_logs', ['api_key'], unique=False)
    op.create_index(op.f('ix_inference_logs_created_at'), 'inference_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_model_id'), 'inference_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_inference_logs_request_id'), 'inference_logs', ['request_id'], unique=False)
    op.create_index('ix_inflog_model_created', 'inference_logs', ['model_id', 'created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('quota_monthly', sa.Integer(), nullable=True),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('quota_reset_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_inflog_model_created', table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_request_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_model_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_created_at'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_api_key'), table_name='inference_logs')
    op.drop_table('inference_logs')
    op.drop_index(op.f('ix_completion_cache_prompt_hash'), table_name='completion_cache')
    op.drop_index(op.f('ix_completion_cache_params_fingerprint'), table_name='completion_cache')
    op.drop_index(op.f('ix_completion_cache_model_id'), table_name='completion_cache')
    op.drop_index(op.f('ix_completion_cache_created_at'), table_name='completion_cache')
    op.drop_index('ix_cache_model_promptfp', table_name='completion_cache')
    op.drop_table('completion_cache')
    # ### end Alembic commands ###
